# набор команд
CMD_MINIMAL = "CMD_MINIMAL"
CMD_NOMINAL = "CMD_NOMINAL"
CMD_OPERATING = "CMD_OPERATING"
CMD_ENABLE_BROADCASTING = "CMD_ENABLE_TRANSMISSION"
CMD_DISABLE_BROADCASTING = "CMD_DISABLE_TRANSMISSION"
CMD_SET_REAL_TIME = "CMD_SET_REAL_TIME"
CMD_ENABLE_DEVICE = "CMD_ENABLE_DEVICE"
CMD_DISABLE_DEVICE = "CMD_DISABLE_DEVICE"
CMD_TRANSCEIVER_SELECT = "CMD_TRANSCEIVER_SELECT"
CMD_DEVICE_COMMAND = "CMD_DEVICE_COMMAND"

CMD_SOFT_SHUTDOWN = "CMD_SOFT_SHUTDOWN"

CMD_RESERVE_MAIN_POWER_ON = "CMD_RESERVE_MAIN_POWER_ON"
CMD_RESERVE_MAIN_POWER_OFF = "CMD_RESERVE_MAIN_POWER_OFF"


