# Generated by Django 2.0.2 on 2018-02-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='student_number',
            field=models.IntegerField(null=True, verbose_name='Номер студенческого'),
        ),
    ]
