# Generated by Django 2.0.2 on 2018-03-19 21:50

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('remote_control', '0003_auto_20180319_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель'), ('administrator', 'Администратор')], max_length=20, verbose_name='Тип пользовател')),
                ('student_number', models.IntegerField(null=True, verbose_name='Номер студенческого')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='commands',
            name='device',
            field=models.ManyToManyField(null=True, to='remote_control.Device'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
