# Generated by Django 2.0.2 on 2018-03-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_control', '0004_auto_20180319_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commands',
            options={'verbose_name': 'Комманда', 'verbose_name_plural': 'Комманды'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Сенсор', 'verbose_name_plural': 'Сенсоры'},
        ),
        migrations.AlterModelOptions(
            name='telemetry',
            options={'verbose_name': 'Телеметрия', 'verbose_name_plural': 'Телеметрия'},
        ),
        migrations.AlterField(
            model_name='commands',
            name='device',
            field=models.ManyToManyField(blank=True, null=True, to='remote_control.Device'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='category',
            field=models.CharField(blank=True, choices=[('CATEGORY_ONBOARD_COMPUTER', 'Бортовой компьютер'), ('CATEGORY_TRANSCEIVER', 'Бортовой модуль связи'), ('CATEGORY_ATTITUDE', 'Бортовой модуль определения ориентации и стабилизации')], max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
