# Generated by Django 2.0.2 on 2018-03-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_control', '0007_auto_20180329_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registration_approved',
            field=models.BooleanField(default=False, verbose_name='Регистрация одобрена?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель')], max_length=20, verbose_name='Тип пользовател'),
        ),
    ]
