# Generated by Django 2.0.2 on 2018-04-04 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remote_control', '0008_auto_20180329_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='remote_control.Commands'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='remote_control.Userprofile'),
        ),
        migrations.AlterField(
            model_name='response',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='remote_control.Request'),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remote_control.Sensor'),
        ),
    ]
