# Generated by Django 2.0.2 on 2018-04-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_control', '0009_auto_20180404_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='device',
            field=models.ManyToManyField(blank=True, null=True, to='remote_control.Device'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='category',
            field=models.CharField(blank=True, choices=[('CATEGORY_ONBOARD_COMPUTER', 'Бортовой компьютер'), ('CATEGORY_TRANSCEIVER', 'Бортовой модуль связи'), ('CATEGORY_ATTITUDE', 'Бортовой модуль определения \n ориентации и стабилизации')], max_length=100, null=True, verbose_name='Категория'),
        ),
    ]
